version: "3"

services:
  mongo:
    image: mongo:4.0-xenial
    ports: 
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  redis:
    image: redis:5.0-alpine
    ports: 
      - "6379:6379"
    volumes:
      - redisdb:/data

volumes:
  mongodb:
  redisdb: