version: 2.1

jobs:
  build:
    environment:
      NODE_ENV: 'test'
    working_directory: ~/guidebook
    docker:
      - image: circleci/node:8.15.0
      - image: mongo:4.1.6-xenial
    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: 
          name: Install project dependencies
          command: npm install --verbose

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json"}}
          paths:
            - node_modules

      - run: npm run lint

      - run:
          name: Run tests
          # When running Jest tests, please use the --runInBand flag: https://circleci.com/docs/2.0/collect-test-data/#jest
          command: npm test -- --runInBand

workflows:
  version: 2.1
  run_build:
    jobs:
      - build
